import { z } from "zod";

export const notificationsFormSchema = z.object({
  emailSecurity: z.boolean(),
  emailUpdates: z.boolean(),
  emailMarketing: z.boolean(),
  pushMessages: z.boolean(),
  pushMentions: z.boolean(),
  pushTasks: z.boolean(),
  emailFrequency: z.string(),
  quietHoursStart: z.string(),
  quietHoursEnd: z.string(),
  channelEmail: z.boolean(),
  channelPush: z.boolean(),
  channelSms: z.boolean(),
  orderUpdatesEmail: z.boolean(),
  orderUpdatesBrowser: z.boolean(),
  orderUpdatesApp: z.boolean(),
  invoiceRemindersEmail: z.boolean(),
  invoiceRemindersBrowser: z.boolean(),
  invoiceRemindersApp: z.boolean(),
  promotionalOffersEmail: z.boolean(),
  promotionalOffersBrowser: z.boolean(),
  promotionalOffersApp: z.boolean(),
  systemMaintenanceEmail: z.boolean(),
  systemMaintenanceBrowser: z.boolean(),
  systemMaintenanceApp: z.boolean(),
  notificationTiming: z.string(),
});

export type NotificationsFormValues = z.infer<typeof notificationsFormSchema>;

export const DEFAULT_NOTIFICATIONS: NotificationsFormValues = {
  emailSecurity: false,
  emailUpdates: true,
  emailMarketing: false,
  pushMessages: true,
  pushMentions: true,
  pushTasks: false,
  emailFrequency: "instant",
  quietHoursStart: "22:00",
  quietHoursEnd: "06:00",
  channelEmail: true,
  channelPush: true,
  channelSms: false,
  orderUpdatesEmail: true,
  orderUpdatesBrowser: true,
  orderUpdatesApp: true,
  invoiceRemindersEmail: true,
  invoiceRemindersBrowser: false,
  invoiceRemindersApp: true,
  promotionalOffersEmail: false,
  promotionalOffersBrowser: true,
  promotionalOffersApp: false,
  systemMaintenanceEmail: true,
  systemMaintenanceBrowser: true,
  systemMaintenanceApp: false,
  notificationTiming: "online",
};
